# Generated by Django 5.2.8 on 2025-12-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_into',
            field=models.DateField(auto_created=True),
        ),
    ]
