# Generated by Django 5.2.8 on 2025-12-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_date_into'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_into',
            field=models.DateField(auto_now_add=True),
        ),
    ]
